"""
ShadowGrid Warden - Simulated Kernel-Level Anti-Cheat

This module simulates a Ring 0 anti-cheat driver that monitors
the GameClient for cheats and reports to the server.
"""

import threading
import time
import hashlib
import json
import sys
import types
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Set
from enum import Enum


class AlertSeverity(Enum):
    """Severity levels for Warden alerts."""
    INFO = 0
    WARNING = 1
    SUSPICIOUS = 2
    CRITICAL = 3


@dataclass
class WardenAlert:
    """An alert generated by Warden scanning."""
    timestamp: float
    severity: AlertSeverity
    category: str
    message: str
    evidence: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IntegrityReport:
    """Report sent from Warden to server."""
    session_id: str
    timestamp: float
    scan_count: int
    integrity_valid: bool
    alerts: List[WardenAlert]
    self_integrity_valid: bool
    code_hashes: Dict[str, str]
    signature: str = ""


class Warden:
    """
    Simulated Ring 0 Anti-Cheat Driver.
    
    Runs in a separate thread and monitors the GameClient for:
    - Unknown attributes (cheat flags)
    - Modified code (monkey-patching)
    - File hash mismatches
    - Self-tampering attempts
    """
    
    # Known legitimate attributes for GameClient
    WHITELIST_ATTRS = {
        'player_id', 'session_id', 'x', 'y', 'position', 'health', 'score',
        'alive', 'ws', 'running', 'strategy', 'move_count', 'is_cheater',
        'stealth_level', 'connected', 'last_move_time'
    }
    
    # Suspicious attribute patterns
    SUSPICIOUS_PATTERNS = ['_cheat', '_hack', '_aimbot', '_wallhack', '_speed']
    
    def __init__(
        self,
        client: Any,
        session_id: str,
        scan_interval: float = 1.0
    ):
        """
        Initialize Warden.
        
        Args:
            client: The GameClient instance to monitor
            session_id: Cryptographic session token
            scan_interval: Seconds between scans
        """
        self.client = client
        self.session_id = session_id
        self.scan_interval = scan_interval
        
        # State
        self.running = False
        self.scan_count = 0
        self.alerts: List[WardenAlert] = []
        self.thread: Optional[threading.Thread] = None
        
        # Baseline integrity data
        self._baseline_computed = False
        self._original_code_objects: Dict[str, Any] = {}
        self._original_code_hashes: Dict[str, str] = {}
        self._file_hashes: Dict[str, str] = {}
        
        # Self-integrity (anti-patch detection)
        self._store_self_integrity()
        
        # Report callback (set by SecurePipeline)
        self._report_callback: Optional[callable] = None
    
    def _store_self_integrity(self) -> None:
        """Store baseline of own code objects for anti-patch detection."""
        methods_to_protect = ['scan_client', 'scan_self', 'send_report', '_compute_hash']
        
        for method_name in methods_to_protect:
            method = getattr(self, method_name, None)
            if method and hasattr(method, '__func__'):
                code_obj = method.__func__.__code__
                self._original_code_objects[method_name] = {
                    'id': id(method.__func__),
                    'code_hash': hashlib.sha256(code_obj.co_code).hexdigest(),
                    'code_obj': code_obj
                }
    
    def compute_baseline(self, client_class: type = None) -> None:
        """
        Compute baseline hashes for integrity verification.
        
        Args:
            client_class: The GameClient class to hash methods from
        """
        if client_class:
            # Hash critical methods
            for method_name in ['move', 'send_input', 'connect']:
                method = getattr(client_class, method_name, None)
                if method and hasattr(method, '__code__'):
                    code = method.__code__
                    self._original_code_hashes[method_name] = hashlib.sha256(
                        code.co_code
                    ).hexdigest()
        
        # Hash strategy files if accessible
        try:
            import importlib.util
            spec = importlib.util.find_spec('shadowgrid.bots.strategies')
            if spec and spec.origin:
                with open(spec.origin, 'rb') as f:
                    self._file_hashes['strategies.py'] = hashlib.sha256(
                        f.read()
                    ).hexdigest()
        except Exception:
            pass
        
        self._baseline_computed = True
    
    def set_report_callback(self, callback: callable) -> None:
        """Set callback for sending reports to server."""
        self._report_callback = callback
    
    def start(self) -> None:
        """Start the Warden scan loop in a daemon thread."""
        if self.running:
            return
        
        self.running = True
        self.thread = threading.Thread(
            target=self._scan_loop,
            daemon=True,
            name=f"Warden-{self.session_id[:8]}"
        )
        self.thread.start()
        print(f"🛡️ Warden started for session {self.session_id[:8]}...")
    
    def stop(self) -> None:
        """Stop the Warden scan loop."""
        self.running = False
        if self.thread:
            self.thread.join(timeout=2.0)
        print(f"🛡️ Warden stopped for session {self.session_id[:8]}")
    
    def _scan_loop(self) -> None:
        """Main scan loop - runs in separate thread."""
        while self.running:
            try:
                # Clear previous alerts
                self.alerts = []
                
                # Perform scans
                self.scan_client()
                self.scan_self()
                
                # Send report
                self.send_report()
                
                self.scan_count += 1
                
            except Exception as e:
                self._add_alert(
                    AlertSeverity.WARNING,
                    "scan_error",
                    f"Scan error: {e}"
                )
            
            time.sleep(self.scan_interval)
    
    def scan_client(self) -> List[WardenAlert]:
        """
        Scan the GameClient for anomalies.
        
        Checks:
        - Unknown attributes in __dict__
        - Suspicious attribute names
        - Modified method code
        """
        if not self.client:
            return []
        
        alerts = []
        
        # Check for unknown attributes
        try:
            client_attrs = set(self.client.__dict__.keys())
            unknown_attrs = client_attrs - self.WHITELIST_ATTRS
            
            for attr in unknown_attrs:
                # Check if it's a suspicious pattern
                severity = AlertSeverity.INFO
                for pattern in self.SUSPICIOUS_PATTERNS:
                    if pattern in attr.lower():
                        severity = AlertSeverity.CRITICAL
                        break
                
                if attr.startswith('_') and not attr.startswith('__'):
                    severity = max(severity, AlertSeverity.SUSPICIOUS)
                
                alert = self._add_alert(
                    severity,
                    "unknown_attribute",
                    f"Unknown attribute detected: {attr}",
                    {'attribute': attr, 'value_type': type(getattr(self.client, attr, None)).__name__}
                )
                alerts.append(alert)
        except Exception as e:
            self._add_alert(AlertSeverity.WARNING, "scan_error", f"Attr scan error: {e}")
        
        # Check for sys.settrace (debugger detection)
        if sys.gettrace() is not None:
            self._add_alert(
                AlertSeverity.SUSPICIOUS,
                "debugger_detected",
                "sys.settrace is active - debugger or tracer detected"
            )
        
        return alerts
    
    def scan_self(self) -> bool:
        """
        Check if Warden itself has been tampered with.
        
        Returns:
            True if integrity valid, False if compromised
        """
        for method_name, baseline in self._original_code_objects.items():
            method = getattr(self, method_name, None)
            
            if not method:
                self._add_alert(
                    AlertSeverity.CRITICAL,
                    "warden_tampering",
                    f"Method {method_name} is missing!"
                )
                return False
            
            # Check function ID
            if not hasattr(method, '__func__'):
                self._add_alert(
                    AlertSeverity.CRITICAL,
                    "warden_tampering",
                    f"Method {method_name} replaced by non-method object!",
                    {'type': type(method).__name__}
                )
                return False

            current_id = id(method.__func__)
            if current_id != baseline['id']:
                self._add_alert(
                    AlertSeverity.CRITICAL,
                    "warden_tampering",
                    f"Method {method_name} function replaced!",
                    {'original_id': baseline['id'], 'current_id': current_id}
                )
                return False
            
            # Check bytecode hash
            current_hash = hashlib.sha256(
                method.__func__.__code__.co_code
            ).hexdigest()
            if current_hash != baseline['code_hash']:
                self._add_alert(
                    AlertSeverity.CRITICAL,
                    "warden_tampering",
                    f"Method {method_name} bytecode modified!",
                    {'original_hash': baseline['code_hash'][:16], 'current_hash': current_hash[:16]}
                )
                return False
        
        return True
    
    def send_report(self) -> None:
        """Send integrity report to server."""
        # Check self integrity first
        self_valid = self.scan_self()
        
        # Check for critical alerts
        integrity_valid = not any(
            a.severity == AlertSeverity.CRITICAL 
            for a in self.alerts
        )
        
        # Build report
        report = IntegrityReport(
            session_id=self.session_id,
            timestamp=time.time(),
            scan_count=self.scan_count,
            integrity_valid=integrity_valid and self_valid,
            alerts=self.alerts.copy(),
            self_integrity_valid=self_valid,
            code_hashes=self._file_hashes.copy()
        )
        
        # Sign report
        report.signature = self._sign_report(report)
        
        # Send via callback
        if self._report_callback:
            try:
                self._report_callback(report)
            except Exception as e:
                print(f"⚠️ Warden report send error: {e}")
    
    def _add_alert(
        self,
        severity: AlertSeverity,
        category: str,
        message: str,
        evidence: Dict[str, Any] = None
    ) -> WardenAlert:
        """Add an alert to the current scan."""
        alert = WardenAlert(
            timestamp=time.time(),
            severity=severity,
            category=category,
            message=message,
            evidence=evidence or {}
        )
        self.alerts.append(alert)
        
        # Log critical alerts immediately
        # Log critical alerts immediately
        if severity == AlertSeverity.CRITICAL:
            # print(f"🚨 WARDEN CRITICAL: {message}") # Disabled to prevent spam
            pass
        
        return alert
    
    def _sign_report(self, report: IntegrityReport) -> str:
        """
        Sign the report with session-specific key.
        
        In real implementation, this would use HMAC with a key
        established during secure handshake.
        """
        data = f"{report.session_id}:{report.timestamp}:{report.integrity_valid}"
        return hashlib.sha256(data.encode()).hexdigest()[:32]
    
    def _compute_hash(self, data: bytes) -> str:
        """Compute SHA-256 hash of data."""
        return hashlib.sha256(data).hexdigest()
    
    def get_status(self) -> Dict[str, Any]:
        """Get current Warden status for dashboard."""
        return {
            'session_id': self.session_id,
            'running': self.running,
            'scan_count': self.scan_count,
            'alert_count': len(self.alerts),
            'critical_alerts': sum(1 for a in self.alerts if a.severity == AlertSeverity.CRITICAL),
            'self_integrity': self.scan_self()
        }
