"""
🛡️ Trepan — Response Parser
Parses the raw model output text into a structured AnalysisResult.

Expected model output format (from training data):
VIOLATION: [State the exact filename and rule broken in 1 short sentence. If no violation, write NONE]
DRIFT SCORE: [0.00 to 1.00]
ACTION: [ACCEPT or REJECT]
"""

import re
import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger("trepan.parser")


@dataclass
class AnalysisResult:
    action: str          # "ACCEPT" or "REJECT"
    drift_score: float   # 0.0 – 1.0
    raw_output: str      # The full model text for display


def parse_response(raw_output: str) -> AnalysisResult:
    """
    Parse the raw model generation into a clean AnalysisResult.

    Args:
        raw_output: The raw text generated by the model after the prompt.

    Returns:
        AnalysisResult with structured fields.
    """
    # Failsafe defaults
    action = "ACCEPT"
    drift_score = 0.0
    violation = "No output"
    
    lines = raw_output.split('\n')
    for line in lines:
        line_upper = line.upper()
        if line_upper.startswith("VIOLATION:"):
            violation = line.replace("VIOLATION:", "").replace("Violation:", "").strip()
        elif line_upper.startswith("DRIFT SCORE:"):
            try:
                # Extract just the numbers
                score_str = ''.join(c for c in line.split(':')[1] if c.isdigit() or c == '.')
                drift_score = float(score_str)
            except:
                pass
        elif line_upper.startswith("ACTION:"):
            if "REJECT" in line_upper:
                action = "REJECT"

    # Hard override: If the model flagged a violation but failed to format the action properly
    if drift_score >= 0.40 and action == "ACCEPT":
        action = "REJECT"

    return AnalysisResult(
        action=action,
        drift_score=drift_score,
        raw_output=raw_output,
    )
